name: Artifact Upload Download 

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Create file
        run: echo "Hello from Job 1" > message.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: message.txt

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: my-artifact

      - name: Show content
        run: cat message.txt

