name: Generate ASCII Art

on: push

jobs:
  ascii:
    if: false
    runs-on: ubuntu-latest
    steps:
      - name: Install figlet in ubuntu
        run: sudo apt-get update && sudo apt-get install -y figlet

      - name: Print ASCII Art
        run: |
          figlet "Ajinkya Pawar"
