name: My First Workflow

on: push

jobs:
    firstjob:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repo
          uses: actions/checkout@v4
          with:
            ref: main
        - name: Multi line commands 
          run: |
            echo "Starting build..."
            mkdir -p output
            echo "Hello, World!" > output/hello.txt
            cat output/hello.txt
            ls -lart
            cat README.md

        #- name: List the files
        #  run: ls -lart 
          
        #- name: Read files
         # run: cat README.md


