name: My First Workflow

on: push

jobs:
    firstjob:
        runs-on: ubuntu-latest
        steps:
        - name: Welcome to GA
          run: echo "Started GA"

        - name: List the files
          run: ls -lart     


