name: Matrix Workflow

on: 
    push

jobs: 
    Matrix:
      strategy:
        matrix:
          os: [ubuntu-latest,windows-latest]
          images: [alpine,nginx]
          exclude:
            - images: [alpine, nginx]
              os: windows-latest
          include:
            - images: hello-world
              os: windows-latest
      if: false      
      runs-on: ${{ matrix.os }}
      steps:
        - name: Check docker info
          run: docker info
        - name: docker pull images ${{ matrix.os }}
          run: docker pull ${{ matrix.images }}