name: Matrix Workflow

on: 
    push

jobs: 
    Matrix:
      strategy:
        matrix:
          os: [ubuntu-latest]
          images: [alpine,nginx]
      runs-on: ${{ matrix.os }}
      steps:
        - name: Check docker info
          run: docker info
        - name: docker pull images ${{ matrix.os }}
          run: docker pull ${{ matrix.images }}