name: Secret Workflow

on: push

jobs:
  Secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use both secret and variable
        run: |
          echo "Environment: ${{ vars.NODE_ENV }}"
          echo "Using secret token (not shown here)"
        env:
          TOKEN: ${{ secrets.MY_SECRET_TOKEN }}
