name: Event Trigger Workflow

on: 
  schedule:
    - cron: "*/1 * * * *"  # Runs every minute
  workflow_dispatch:  # Add this for triggered the workflow


jobs:
  Event:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Triggered option checks
        run: |
          echo "Environment: $NODE_ENV"
          echo "Using secret token (value hidden)"
          sleep 72s
        env:
          NODE_ENV: ${{ vars.NODE_ENV }}
          TOKEN: ${{ secrets.MY_SECRET_TOKEN }}
