name: Event Trigger Workflow

on: 
  schedule:
    - cron: "*/1 * * * *"  # Runs every minute

jobs:
  Event:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Triggered option checks
        run: |
          echo "Environment: $NODE_ENV"
          echo "Using secret token (value hidden)"
        env:
          NODE_ENV: ${{ vars.NODE_ENV }}
          TOKEN: ${{ secrets.MY_SECRET_TOKEN }}
